DROP FUNCTION IF EXISTS SP_KYC_GET_OFFICE;

CREATE OR REPLACE FUNCTION SP_KYC_GET_OFFICE(
    P_ID INTEGER,
    P_CITY VARCHAR,
    P_STATE VARCHAR,
    P_POSTAL_CODE VARCHAR,
    P_ACTIVE BOOLEAN DEFAULT TRUE)
RETURNS TABLE (
    ID INTEGER,
    NAME VARCHAR(50),
    STREET VARCHAR(50),
    NEIGHBORHOOD VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    POSTAL_CODE VARCHAR(5),
    BUSINESS_HOURS VARCHAR(40),
    LATITUDE VARCHAR(15),
    LONGITUDE VARCHAR(15),
    ACTIVE BOOLEAN
)
LANGUAGE plpgsql
AS $$
DECLARE
    V_QUERY VARCHAR;
BEGIN

    V_QUERY = 'SELECT * FROM KYC_OFFICE WHERE ACTIVE=' || P_ACTIVE;

    IF COALESCE(P_ID,0) <> 0 THEN
        V_QUERY = V_QUERY || ' AND ID='|| P_ID ;
    END IF;

    IF COALESCE(P_CITY,'') <> '' THEN
        V_QUERY = V_QUERY || FORMAT(' AND LOWER(CITY)=LOWER(%L) ',P_CITY);
    END IF;

    IF COALESCE(P_STATE,'') <> '' THEN
        V_QUERY = V_QUERY || FORMAT(' AND LOWER(STATE)=LOWER(%L) ',P_STATE);
    END IF;

    IF COALESCE(P_POSTAL_CODE,'') <> '' THEN
        V_QUERY = V_QUERY || FORMAT(' AND LOWER(POSTAL_CODE)=LOWER(%L) ',P_POSTAL_CODE);
    END IF;
    
    RETURN QUERY EXECUTE V_QUERY;

END; $$;