-- USERS DROP CONSTRAINTS FK
ALTER TABLE KYC_CUSTOMER_ADDRESS DROP CONSTRAINT IF EXISTS FK_KYC_CUSTOMER_ADDRESS_ID_CUSTOMER;
ALTER TABLE KYC_CUSTOMER DROP CONSTRAINT IF EXISTS KYC_CUSTOMER_ID_USER;

-- EXECUTIVES DROP CONSTRAINTS FK
ALTER TABLE KYC_EXECUTIVE DROP CONSTRAINT IF EXISTS KYC_EXECUTIVE_ID_USER;
ALTER TABLE KYC_EXECUTIVE DROP CONSTRAINT IF EXISTS KYC_EXECUTIVE_ID_BRANCH;

-- USERS DROP CONSTRAINTS FK
ALTER TABLE KYC_LOGIN_HISTORIC DROP CONSTRAINT IF EXISTS FK_KYC_LOGIN_HISTORIC_ID_USER;
ALTER TABLE KYC_LOGIN_USER_INFO DROP CONSTRAINT IF EXISTS FK_KYC_LOGIN_USER_INFO_ID_USER;
ALTER TABLE KYC_LOGIN_HISTORIC DROP CONSTRAINT IF EXISTS FK_KYC_LOGIN_HISTORIC_ID_CHANNEL;
ALTER TABLE KYC_USER DROP CONSTRAINT IF EXISTS KYC_USER_USER_TYPE;

-- CAMPAIGNS DROP CONSTRAINTS FK
ALTER TABLE KYC_OFFERS DROP CONSTRAINT IF EXISTS FK_KYC_OFFERS_ID_CAMPAIGN;
ALTER TABLE KYC_OFFERS DROP CONSTRAINT IF EXISTS FK_STATUS;
ALTER TABLE KYC_TEMP_OFFERS_ERRORS DROP CONSTRAINT IF EXISTS FK_ID_TEMP_OFFER;

-- REPORTS DROP CONSTRAINTS FK
ALTER TABLE KYC_RECORD_REPORTS DROP CONSTRAINT IF EXISTS FK_REPORT_TYPE_ID;
ALTER TABLE KYC_RECORD_REPORTS DROP CONSTRAINT IF EXISTS FK_RECORD_REPORTS_ID_CUSTOMER;

-- POSTAL CODES DROP CONSTRAINTS FK
ALTER TABLE KYC_POSTAL_CODES_NEIGHBORHOOD DROP CONSTRAINT IF EXISTS FK_POSTAL_CODES;


-- CATALOGS DROP CONSTRAINTS PK
ALTER TABLE KYC_SERVICES DROP CONSTRAINT IF EXISTS kyc_services_pkey;
ALTER TABLE KYC_PAYMENT_METHODS DROP CONSTRAINT IF EXISTS kyc_payment_methods_pkey;
ALTER TABLE KYC_CHANNEL DROP CONSTRAINT IF EXISTS kyc_channel_pkey;
ALTER TABLE KYC_SERVICE_STATUS DROP CONSTRAINT IF EXISTS kyc_service_status_pkey;
ALTER TABLE KYC_STATES_COUNTRY DROP CONSTRAINT IF EXISTS kyc_states_country_pkey;
ALTER TABLE KYC_TRANSACTION_STATUS DROP CONSTRAINT IF EXISTS kyc_transaction_status_pkey;
ALTER TABLE KYC_PAYMENT_STATUS DROP CONSTRAINT IF EXISTS kyc_payment_status_pkey;
ALTER TABLE KYC_USER_TYPE DROP CONSTRAINT IF EXISTS kyc_user_type_pkey;
ALTER TABLE KYC_BATCH_ID DROP CONSTRAINT IF EXISTS kyc_batch_id_pkey;
ALTER TABLE KYC_REPORT_TYPE DROP CONSTRAINT IF EXISTS kyc_report_type_pkey;
ALTER TABLE KYC_STATUS_OFFER DROP CONSTRAINT IF EXISTS kyc_status_offer_pkey;
ALTER TABLE KYC_OFFICE DROP CONSTRAINT IF EXISTS kyc_office_pkey;

--- PARAMETERS DROP CONSTRAINTS PK
ALTER TABLE KYC_PARAMETERS DROP CONSTRAINT IF EXISTS kyc_parameters_pkey;

-- CUSTOMERS DROP CONSTRAINTS PK
ALTER TABLE KYC_CUSTOMER DROP CONSTRAINT IF EXISTS kyc_customer_pkey;

-- EXECUTIVES DROP CONSTRAINTS
ALTER TABLE KYC_EXECUTIVE DROP CONSTRAINT IF EXISTS kyc_executive_pkey;

--- USERS DROP CONSTRAINTS PK
ALTER TABLE KYC_USER DROP CONSTRAINT IF EXISTS kyc_user_pkey;
ALTER TABLE KYC_LOGIN_HISTORIC DROP CONSTRAINT IF EXISTS kyc_login_historic_pkey;
ALTER TABLE KYC_LOGIN_USER_INFO DROP CONSTRAINT IF EXISTS kyc_login_user_info_pkey;

--- CAMPAIGNS DROP CONSTRAINTS
ALTER TABLE KYC_TEMP_OFFERS DROP CONSTRAINT IF EXISTS kyc_temp_offers_pkey;
ALTER TABLE KYC_OFFERS DROP CONSTRAINT IF EXISTS kyc_offers_pkey;
ALTER TABLE KYC_CAMPAIGN DROP CONSTRAINT IF EXISTS kyc_campaign_pkey;
ALTER TABLE KYC_TEMP_OFFERS_ERRORS DROP CONSTRAINT IF EXISTS kyc_temp_offers_errors_pkey;

--- REPORTS DROP CONSTRAINTS
ALTER TABLE KYC_RECORD_REPORTS DROP CONSTRAINT IF EXISTS kyc_record_reports_pkey;

--- POSTAL CODES DROP CONSTRAINTS
ALTER TABLE KYC_POSTAL_CODES_CENTRAL DROP CONSTRAINT IF EXISTS kyc_postal_codes_central_pkey;
ALTER TABLE KYC_POSTAL_CODES_NEIGHBORHOOD DROP CONSTRAINT IF EXISTS kyc_postal_codes_neighborhood_pkey;


-- CATALOGS ADD CONSTRAINTS
ALTER TABLE KYC_SERVICES ADD PRIMARY KEY(ID);
ALTER TABLE KYC_PAYMENT_METHODS ADD PRIMARY KEY(ID);
ALTER TABLE KYC_CHANNEL ADD PRIMARY KEY(ID);
ALTER TABLE KYC_SERVICE_STATUS ADD PRIMARY KEY(ID);
ALTER TABLE KYC_STATES_COUNTRY ADD PRIMARY KEY(ID);
ALTER TABLE KYC_TRANSACTION_STATUS ADD PRIMARY KEY(ID);
ALTER TABLE KYC_PAYMENT_STATUS ADD PRIMARY KEY (ID);
ALTER TABLE KYC_USER_TYPE ADD PRIMARY KEY(ID);
ALTER TABLE KYC_BATCH_ID ADD PRIMARY KEY(ID);
ALTER TABLE KYC_REPORT_TYPE ADD PRIMARY KEY(ID);
ALTER TABLE KYC_STATUS_OFFER ADD PRIMARY KEY(ID);
ALTER TABLE KYC_OFFICE ADD PRIMARY KEY(ID);

--- PARAMETERS ADD CONSTRAINTS
ALTER TABLE KYC_PARAMETERS ADD PRIMARY KEY(ID);

--- USERS ADD CONSTRAINTS
ALTER TABLE KYC_USER ADD PRIMARY KEY(ID);
ALTER TABLE KYC_LOGIN_HISTORIC ADD PRIMARY KEY(ID);
ALTER TABLE KYC_LOGIN_USER_INFO ADD PRIMARY KEY(ID_USER);

ALTER TABLE KYC_LOGIN_HISTORIC ADD CONSTRAINT FK_KYC_LOGIN_HISTORIC_ID_USER
FOREIGN KEY (ID_USER) REFERENCES KYC_USER(ID) ON DELETE CASCADE;

ALTER TABLE KYC_LOGIN_USER_INFO ADD CONSTRAINT FK_KYC_LOGIN_USER_INFO_ID_USER
FOREIGN KEY (ID_USER) REFERENCES KYC_USER(ID) ON DELETE CASCADE;

ALTER TABLE KYC_LOGIN_HISTORIC ADD CONSTRAINT FK_KYC_LOGIN_HISTORIC_ID_CHANNEL
FOREIGN KEY (ID_CHANNEL) REFERENCES KYC_CHANNEL(ID) ON DELETE CASCADE;

ALTER TABLE KYC_USER ADD CONSTRAINT KYC_USER_USER_TYPE
FOREIGN KEY (USER_TYPE) REFERENCES KYC_USER_TYPE(ID) ON DELETE CASCADE;

--- CUSTOMERS ADD CONSTRAINTS
ALTER TABLE KYC_CUSTOMER ADD PRIMARY KEY (ID);

ALTER TABLE KYC_CUSTOMER_ADDRESS ADD CONSTRAINT FK_KYC_CUSTOMER_ADDRESS_ID_CUSTOMER
FOREIGN KEY (ID_CUSTOMER) REFERENCES KYC_CUSTOMER(ID) ON DELETE CASCADE;

ALTER TABLE KYC_CUSTOMER ADD CONSTRAINT KYC_CUSTOMER_ID_USER
FOREIGN KEY (ID) REFERENCES KYC_USER(ID) ON DELETE CASCADE;

-- EXECUTIVES ADD CONSTRAINTS
ALTER TABLE KYC_EXECUTIVE ADD PRIMARY KEY(ID);

ALTER TABLE KYC_EXECUTIVE ADD CONSTRAINT KYC_EXECUTIVE_ID_USER
FOREIGN KEY (ID_USER) REFERENCES KYC_USER(ID) ON DELETE CASCADE;

ALTER TABLE KYC_EXECUTIVE ADD CONSTRAINT KYC_EXECUTIVE_ID_BRANCH
FOREIGN KEY (ID_BRANCH) REFERENCES KYC_OFFICE(ID) ON DELETE SET NULL;

--- CAMPAIGNS ADD CONSTRAINTS
ALTER TABLE KYC_TEMP_OFFERS ADD PRIMARY KEY(ID);
ALTER TABLE KYC_OFFERS ADD PRIMARY KEY(ID);
ALTER TABLE KYC_CAMPAIGN ADD PRIMARY KEY(ID);
ALTER TABLE KYC_TEMP_OFFERS_ERRORS ADD PRIMARY KEY(ID);

ALTER TABLE KYC_OFFERS ADD CONSTRAINT FK_KYC_OFFERS_ID_CAMPAIGN
FOREIGN KEY (ID_CAMPAIGN) REFERENCES KYC_OFFERS(ID) ON DELETE CASCADE;

ALTER TABLE KYC_OFFERS ADD CONSTRAINT FK_STATUS
FOREIGN KEY (STATUS) REFERENCES KYC_STATUS_OFFER(ID) ON DELETE CASCADE;

ALTER TABLE KYC_TEMP_OFFERS_ERRORS ADD CONSTRAINT FK_ID_TEMP_OFFER
FOREIGN KEY(ID_TEMP_OFFER) REFERENCES KYC_TEMP_OFFERS(ID) ON DELETE CASCADE;

--- REPORTS ADD CONSTRAINTS
ALTER TABLE KYC_RECORD_REPORTS ADD PRIMARY KEY(ID);

ALTER TABLE KYC_RECORD_REPORTS ADD CONSTRAINT FK_REPORT_TYPE_ID FOREIGN KEY(REPORT_TYPE_ID)
REFERENCES KYC_REPORT_TYPE(ID) ON DELETE SET NULL;

ALTER TABLE KYC_RECORD_REPORTS ADD CONSTRAINT FK_RECORD_REPORTS_ID_CUSTOMER FOREIGN KEY(ID_CUSTOMER)
REFERENCES KYC_CUSTOMER(ID) ON DELETE CASCADE;

--- POSTAL CODES ADD CONSTRAINTS
ALTER TABLE KYC_POSTAL_CODES_CENTRAL ADD PRIMARY KEY(POSTAL_CODE, VERSION);
ALTER TABLE KYC_POSTAL_CODES_NEIGHBORHOOD ADD PRIMARY KEY(ID_NEIGHBORHOOD, RELATED_POSTAL_CODE, RELATED_VERSION);

ALTER TABLE KYC_POSTAL_CODES_NEIGHBORHOOD ADD CONSTRAINT FK_POSTAL_CODES FOREIGN KEY(RELATED_POSTAL_CODE, RELATED_VERSION)
REFERENCES KYC_POSTAL_CODES_CENTRAL(POSTAL_CODE,VERSION) ON DELETE CASCADE;