DROP TABLE IF EXISTS KYC_SERVICES;
DROP TABLE IF EXISTS KYC_SERVICE_STATUS;
DROP TABLE IF EXISTS KYC_CHANNEL;
DROP TABLE IF EXISTS KYC_PAYMENT_METHODS;
DROP TABLE IF EXISTS KYC_STATES_COUNTRY;
DROP TABLE IF EXISTS KYC_TRANSACTION_STATUS;
DROP TABLE IF EXISTS KYC_PAYMENT_STATUS;
DROP TABLE IF EXISTS KYC_USER_TYPE;
DROP TABLE IF EXISTS KYC_BATCH_ID;
DROP TABLE IF EXISTS KYC_REPORT_TYPE;
DROP TABLE IF EXISTS KYC_STATUS_OFFER;
DROP TABLE IF EXISTS KYC_OFFICE;

CREATE TABLE KYC_SERVICES(
    ID SERIAL,
    NAME VARCHAR(50) NOT NULL,
    COST VARCHAR(10) NOT NULL
);

CREATE TABLE KYC_SERVICE_STATUS(
    ID SERIAL,
    DESCRIPTION VARCHAR(20) NOT NULL
);

CREATE TABLE KYC_CHANNEL(
    ID SERIAL,
    DESCRIPTION VARCHAR(20) NOT NULL
);

CREATE TABLE KYC_PAYMENT_METHODS(
    ID SERIAL,
    DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE KYC_STATES_COUNTRY(
    ID SERIAL,
    CODE VARCHAR(3),
    DESCRIPTION VARCHAR(50)
);

CREATE TABLE KYC_TRANSACTION_STATUS(
    ID SERIAL,
    DESCRIPTION VARCHAR(10)
);

CREATE TABLE KYC_PAYMENT_STATUS(
    ID SERIAL,
    DESCRIPTION VARCHAR(15)
);

CREATE TABLE KYC_USER_TYPE(
	ID SERIAL,
	DESCRIPTION VARCHAR(20)
);

CREATE TABLE KYC_BATCH_ID(
    ID SERIAL,
    DESCRIPTION VARCHAR(100)
);

CREATE TABLE KYC_REPORT_TYPE(
	ID SERIAL,
	DESCRIPTION VARCHAR(20)
);

CREATE TABLE KYC_STATUS_OFFER(
	ID SERIAL,
	DESCRIPTION VARCHAR(20)
);

CREATE TABLE KYC_OFFICE(
    ID INTEGER,
    NAME VARCHAR(50),
    STREET VARCHAR(50),
    NEIGHBORHOOD VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    POSTAL_CODE VARCHAR(5),
    BUSINESS_HOURS VARCHAR(40),
    LATITUDE VARCHAR(15),
    LONGITUDE VARCHAR(15),
    ACTIVE BOOLEAN
);

CREATE TABLE KYC_OFFICE_TMP(
    ID INTEGER,
    NAME VARCHAR(50),
    STREET VARCHAR(50),
    NEIGHBORHOOD VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    POSTAL_CODE VARCHAR(5),
    BUSINESS_HOURS VARCHAR(40),
    LATITUDE VARCHAR(15),
    LONGITUDE VARCHAR(15),
    ACTIVE BOOLEAN
);