DROP TABLE IF EXISTS KYC_EXECUTIVE;

CREATE TABLE KYC_EXECUTIVE(
    ID SERIAL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    SECOND_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    SECOND_LAST_NAME VARCHAR(50),
    RFC VARCHAR(13) NOT NULL,
    PHONE VARCHAR(10),
    EXTENSION VARCHAR(3),
    EMAIL VARCHAR(50) NOT NULL,
    ID_BRANCH INTEGER,
    STATUS BOOLEAN NOT NULL,
    DATE_CREATION DATE NOT NULL,
    DATE_UPDATED DATE,
    ID_USER INTEGER,
    BATCH_OPERATION_CONTROL INTEGER
);