
CREATE DATABASE kyc_database;

CREATE USER kyc_user WITH ENCRYPTED PASSWORD 'kyc_pass';

ALTER DATABASE kyc_database OWNER TO kyc_user;

GRANT ALL PRIVILEGES ON DATABASE kyc_database TO kyc_user;

CREATE EXTENSION IF NOT EXISTS pgcrypto;