DROP TABLE IF EXISTS KYC_PAYMENT;
DROP TABLE IF EXISTS KYC_TRANSACTION;
DROP TABLE IF EXISTS KYC_CUSTOMER_PAYMENT_METHOD;

CREATE TABLE KYC_PAYMENT(
    FOLIO SERIAL,
    CHANNEL INTEGER,
    PAYMENT_METHOD INTEGER,
    AMOUNT DECIMAL,
    MOTIVE VARCHAR(50),
    ACCOUNT VARCHAR(40),
    REFERENCE VARCHAR(12),
    ID_STATUS INTEGER,
    ID_BILL INTEGER,
    ID_PAYMENT_OFFICE INTEGER,
    ID_USER_TRANSACTOR INTEGER,
    ID_CUSTOMER INTEGER,
    DATE_PAYMENT TIMESTAMP NOT NULL
);

CREATE TABLE KYC_TRANSACTION(
    ID SERIAL,
    ID_STATUS INTEGER,
    FOLIO_PAYMENT INTEGER,
    DATE_TRANSACTION TIMESTAMP
);

CREATE TABLE KYC_CUSTOMER_PAYMENT_METHOD(
    ID SERIAL,
    ID_CUSTOMER INTEGER,
    ID_PAYMENT_METHOD INTEGER,
    ACCOUNT VARCHAR(40),
    AUTHORIZE BOOLEAN,
    ACTIVE BOOLEAN,
    DIRECT_DEBIT BOOLEAN,
    CREATION_DATE TIMESTAMP
);