DROP TABLE IF EXISTS KYC_POSTAL_CODES_CENTRAL;
DROP TABLE IF EXISTS KYC_POSTAL_CODES_NEIGHBORHOOD;


CREATE TABLE KYC_POSTAL_CODES_CENTRAL(
    POSTAL_CODE VARCHAR(5),
    VERSION INTEGER,
    ID_CITY INTEGER,
    CITY VARCHAR(50),
    ID_STATE INTEGER,
    STATE VARCHAR(50),
    UPLOAD_DATE TIMESTAMP
);

CREATE TABLE KYC_POSTAL_CODES_NEIGHBORHOOD(
    ID_NEIGHBORHOOD INTEGER,
    NEIGHBORHOOD VARCHAR(80),
    UPLOAD_DATE TIMESTAMP,
    RELATED_POSTAL_CODE VARCHAR(5),
    RELATED_VERSION INTEGER
);