DROP TABLE IF EXISTS KYC_PARAMETERS;

CREATE TABLE KYC_PARAMETERS(
    ID SERIAL,
    PARAM_KEY VARCHAR(40) NOT NULL,
    PARAM_VALUE VARCHAR(200),
    CREATION_DATE DATE NOT NULL,
    UPDATED_DATE DATE
);