DROP TABLE IF EXISTS KYC_CUSTOMER_BILL;

CREATE TABLE KYC_CUSTOMER_BILL_CONTROL(
    ID SERIAL,
    TAXES NUMERIC,
    SUBTOTAL_AMOUNT NUMERIC,
    TOTAL_AMOUNT NUMERIC,
    ID_CUSTOMER INTEGER,
    SETTLED BOOLEAN,
    ID_STATUS INTEGER,
    ISSUE_DATE TIMESTAMP,
    BILLING_START_DATE DATE,
    BILLING_FINISH_DATE DATE,
    PAYMENT_DUE_DATE DATE,
    SETTLEMENT_DATE TIMESTAMP
);