DROP TABLE IF EXISTS KYC_CUSTOMER_SERVICE;
DROP TABLE IF EXISTS KYC_CUSTOMER_APPLICATION;

CREATE TABLE KYC_CUSTOMER_APPLICATION(
    ID SERIAL,
    PROMOTIONAL_CODE VARCHAR(12),
    ID_CHANNEL INTEGER,
    ID_OFFICE INTEGER,
    ID_CUSTOMER INTEGER,
    ID_EXECUTIVE INTEGER,
    ID_OFFER INTEGER,
    PROMOTIONS JSONB,
    CREATION_DATE TIMESTAMP
);

CREATE TABLE KYC_CUSTOMER_SERVICE(
    ID SERIAL,
    FOLIO INTEGER,
    ID_SERVICE INTEGER,
    SERVICE_COST NUMERIC,
    ACTIVE BOOLEAN,
    CREATION_DATE TIMESTAMP,
    MODIFICATION_DATE TIMESTAMP
);