DROP TABLE IF EXISTS KYC_CUSTOMER_SERVICE;

CREATE TABLE KYC_CUSTOMER_SERVICE(
    ID SERIAL,
    ID_SERVICE INTEGER,
    PROMOTIONAL_CODE VARCHAR(12),
    SERVICE_COST NUMERIC,
    ID_CHANNEL INTEGER,
    ID_OFFICE INTEGER,
    ACTIVE BOOLEAN,
    ID_CUSTOMER INTEGER,
    ID_EXECUTIVE INTEGER,
    CREATION_DATE TIMESTAMP,
    MODIFICATION_DATE TIMESTAMP
);