DROP TABLE IF EXISTS KYC_CUSTOMER;
DROP TABLE IF EXISTS KYC_CUSTOMER_ADDRESS;

CREATE TABLE KYC_CUSTOMER(
    ID SERIAL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    SECOND_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50) NOT NULL,
    SECOND_LAST_NAME VARCHAR(50),
    RFC VARCHAR(13),
    AGE VARCHAR(2),
    HOME_PHONE VARCHAR(10),
    CELL_PHONE VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ACTIVE BOOLEAN,
    DATE_CREATED DATE NOT NULL,
    DATE_MODIFIED DATE
);

CREATE TABLE KYC_CUSTOMER_ADDRESS(
    ID_CUSTOMER INTEGER,
    STREET VARCHAR(20) NOT NULL,
    STREET_NUMBER VARCHAR(5),
    NEIGHBOURHOOD VARCHAR(20) NOT NULL,
    ID_STATE INTEGER NOT NULL,
    DATE_CREATED DATE NOT NULL,
    DATE_MODIFIED DATE
);

ALTER TABLE KYC_CUSTOMER ADD PRIMARY KEY (ID);

ALTER TABLE KYC_CUSTOMER_ADDRESS ADD CONSTRAINT FK_KYC_CUSTOMER_ADDRESS_ID_CUSTOMER
FOREIGN KEY (ID_CUSTOMER) REFERENCES KYC_CUSTOMER(ID) ON DELETE CASCADE;

ALTER TABLE KYC_CUSTOMER_ADDRESS ADD CONSTRAINT FK_KYC_CUSTOMER_ADDRESS_ID_STATE
FOREIGN KEY (ID_STATE) REFERENCES KYC_STATES_COUNTRY(ID) ON DELETE CASCADE;