CREATE TABLE KYC_RECORD_REPORTS(
    ID UUID,
    RELATED_FOLIO INTEGER,
    OUTPUT_DATE TIMESTAMP NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    REPORT_TYPE_ID INTEGER,
    MIME_TYPE VARCHAR(40),
    REPORT BYTEA
);