DROP TABLE IF EXISTS KYC_SERVICES;
DROP TABLE IF EXISTS KYC_SERVICE_STATUS;
DROP TABLE IF EXISTS KYC_CHANNEL;
DROP TABLE IF EXISTS KYC_PAYMENT_METHODS;
DROP TABLE IF EXISTS KYC_STATES_COUNTRY;
DROP TABLE IF EXISTS KYC_TRANSACTION_STATUS;
DROP TABLE IF EXISTS KYC_PAYMENT_STATUS;
DROP TABLE IF EXISTS KYC_USER_TYPE;
DROP TABLE IF EXISTS KYC_BATCH_ID;
DROP TABLE IF EXISTS KYC_BATCH_ERROR_TYPE;
DROP TABLE IF EXISTS KYC_BATCH_STATUS;
DROP TABLE IF EXISTS KYC_REPORT_TYPE;

CREATE TABLE KYC_SERVICES(
    ID SERIAL,
    NAME VARCHAR(50) NOT NULL,
    COST VARCHAR(10) NOT NULL
);

CREATE TABLE KYC_SERVICE_STATUS(
    ID SERIAL,
    DESCRIPTION VARCHAR(20) NOT NULL
);

CREATE TABLE KYC_CHANNEL(
    ID SERIAL,
    DESCRIPTION VARCHAR(20) NOT NULL
);

CREATE TABLE KYC_PAYMENT_METHODS(
    ID SERIAL,
    DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE KYC_STATES_COUNTRY(
    ID SERIAL,
    CODE VARCHAR(3),
    DESCRIPTION VARCHAR(50)
);

CREATE TABLE KYC_TRANSACTION_STATUS(
    ID SERIAL,
    DESCRIPTION VARCHAR(10)
);

CREATE TABLE KYC_PAYMENT_STATUS(
    ID SERIAL,
    DESCRIPTION VARCHAR(15)
);

CREATE TABLE KYC_USER_TYPE(
	ID SERIAL,
	DESCRIPTION VARCHAR(20)
);

CREATE TABLE KYC_BATCH_ID(
    ID SERIAL,
    DESCRIPTION VARCHAR(20)
);

CREATE TABLE KYC_BATCH_ERROR_TYPE(
    ID SERIAL,
    DESCRIPTION VARCHAR(40)
);

CREATE TABLE KYC_BATCH_STATUS(
	ID SERIAL,
	DESCRIPTION VARCHAR(20)
);

CREATE TABLE KYC_REPORT_TYPE(
	ID SERIAL,
	DESCRIPTION VARCHAR(20)
);

ALTER TABLE KYC_SERVICES ADD PRIMARY KEY(ID);
ALTER TABLE KYC_PAYMENT_METHODS ADD PRIMARY KEY(ID);
ALTER TABLE KYC_CHANNEL ADD PRIMARY KEY(ID);
ALTER TABLE KYC_SERVICE_STATUS ADD PRIMARY KEY(ID);
ALTER TABLE KYC_STATES_COUNTRY ADD PRIMARY KEY(ID);
ALTER TABLE KYC_TRANSACTION_STATUS ADD PRIMARY KEY(ID);
ALTER TABLE KYC_PAYMENT_STATUS ADD PRIMARY KEY (ID);
ALTER TABLE KYC_USER_TYPE ADD PRIMARY KEY(ID);
ALTER TABLE KYC_BATCH_ID ADD PRIMARY KEY(ID);
ALTER TABLE KYC_BATCH_ERROR_TYPE ADD PRIMARY KEY(ID);
ALTER TABLE KYC_BATCH_STATUS ADD PRIMARY KEY(ID);
ALTER TABLE KYC_REPORT_TYPE ADD PRIMARY KEY(ID);

INSERT INTO KYC_SERVICES(NAME,COST) VALUES('Solo Internet','15');
INSERT INTO KYC_SERVICES(NAME,COST) VALUES('Internet y Netflix','25');
INSERT INTO KYC_SERVICES(NAME,COST) VALUES('Solo TV Cable','14');
INSERT INTO KYC_SERVICES(NAME,COST) VALUES('Internet y TV Cable','28');
INSERT INTO KYC_SERVICES(NAME,COST) VALUES('Internet, TV Cable y Netflix','30');

INSERT INTO KYC_SERVICE_STATUS(DESCRIPTION) VALUES('Activo');
INSERT INTO KYC_SERVICE_STATUS(DESCRIPTION) VALUES('Suspendido');
INSERT INTO KYC_SERVICE_STATUS(DESCRIPTION) VALUES('Cancelado');

INSERT INTO KYC_CHANNEL(DESCRIPTION) VALUES('Sucursal');
INSERT INTO KYC_CHANNEL(DESCRIPTION) VALUES('Mobile');
INSERT INTO KYC_CHANNEL(DESCRIPTION) VALUES('Online');

INSERT INTO KYC_PAYMENT_METHODS(DESCRIPTION) VALUES('Ventanilla Bancaria');
INSERT INTO KYC_PAYMENT_METHODS(DESCRIPTION) VALUES('Paypal');
INSERT INTO KYC_PAYMENT_METHODS(DESCRIPTION) VALUES('Tarjeta de Credito');
INSERT INTO KYC_PAYMENT_METHODS(DESCRIPTION) VALUES('Tiendas de autoservicio');

INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Aguascalientes','AS');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Baja California','BC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Baja California Sur','BS');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Campeche','CC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Chiapas','CS');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Chihuahua','CH');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Ciudad de Mexico','DF');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Coahuila','CL');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Colima','CM');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Durango','DG');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Guanajuato','GT');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Guerrero','GR');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Hidalgo','HG');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Jalisco','JC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Estado de Mexico','MC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Michoacan','MN');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Morelos','MS');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Nayarit','NT');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Nuevo Leon','NL');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Oaxaca','OC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Puebla','PL');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Queretaro','QO');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Quintana Roo','QR');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('San Luis Potosi','SP');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Sinaloa','SL');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Sonora','SR');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Tabasco','TC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Tamaulipas','TS');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Tlaxcala','TL');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Veracruz','VZ');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Yucatan','YN');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Zacatecas','ZS');

INSERT INTO KYC_PAYMENT_STATUS(DESCRIPTION) VALUES('REJECTED');
INSERT INTO KYC_PAYMENT_STATUS(DESCRIPTION) VALUES('PAID');
INSERT INTO KYC_PAYMENT_STATUS(DESCRIPTION) VALUES('ONGOING');

INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('SUCCESS');
INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('APPROVED');
INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('PENDING');
INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('SEND');
INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('DECLINED');
INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('FAILED');

INSERT INTO KYC_USER_TYPE(DESCRIPTION) VALUES('CUSTOMER');
INSERT INTO KYC_USER_TYPE(DESCRIPTION) VALUES('EXECUTIVE');

INSERT INTO KYC_BATCH_ID(DESCRIPTION) VALUES('KYC_BILLING');
INSERT INTO KYC_BATCH_ID(DESCRIPTION) VALUES('KYC_PAYMENTS_SB');
INSERT INTO KYC_BATCH_ID(DESCRIPTION) VALUES('KYC_PAYMENTS_SK');
INSERT INTO KYC_BATCH_ID(DESCRIPTION) VALUES('KYC_PAYMENTS_SR');

INSERT INTO KYC_BATCH_ERROR_TYPE(DESCRIPTION) VALUES('BAD STRUCTURE IN FILE');
INSERT INTO KYC_BATCH_ERROR_TYPE(DESCRIPTION) VALUES('FILE NOT FOUND OR NON-EXISTENT');
INSERT INTO KYC_BATCH_ERROR_TYPE(DESCRIPTION) VALUES('A ERROR HAS OCCURRED IN THE SYSTEM');
INSERT INTO KYC_BATCH_ERROR_TYPE(DESCRIPTION) VALUES('RESPONSE FILE COULD NOT PROCESS');

INSERT INTO KYC_BATCH_STATUS(DESCRIPTION) VALUES('FAILED');
INSERT INTO KYC_BATCH_STATUS(DESCRIPTION) VALUES('SUCCEEDED');
INSERT INTO KYC_BATCH_STATUS(DESCRIPTION) VALUES('ONGOING');

INSERT INTO KYC_REPORT_TYPE(DESCRIPTION) VALUES('RECEIPT');
INSERT INTO KYC_REPORT_TYPE(DESCRIPTION) VALUES('INFO_SERVICE');