DROP TABLE IF EXISTS KYC_PARAMETERS;

CREATE TABLE KYC_PARAMETERS(
    ID SERIAL,
    PARAM_KEY VARCHAR(40) NOT NULL,
    PARAM_VALUE VARCHAR(200),
    CREATION_DATE DATE NOT NULL,
    UPDATED_DATE DATE
);

ALTER TABLE KYC_PARAMETERS ADD PRIMARY KEY(ID);

INSERT INTO KYC_PARAMETERS(PARAM_KEY,PARAM_VALUE,CREATION_DATE) VALUES('KYC_SHARED_KEY','G+KbPeShVmYq3t6w9z$C&E)H@McQfTjW',CURRENT_DATE);
INSERT INTO KYC_PARAMETERS(PARAM_KEY,PARAM_VALUE,creation_date) VALUES('KYC_SESSION_TIMEOUT','15',CURRENT_DATE);
INSERT INTO KYC_PARAMETERS(PARAM_KEY,PARAM_VALUE,creation_date) VALUES('KYC_FAIL_LOGIN_ATTEMPTS','3',CURRENT_DATE);