
-- CATALOGS
INSERT INTO KYC_SERVICES(NAME,COST) VALUES('Solo Internet','15');
INSERT INTO KYC_SERVICES(NAME,COST) VALUES('Internet y Netflix','25');
INSERT INTO KYC_SERVICES(NAME,COST) VALUES('Solo TV Cable','14');
INSERT INTO KYC_SERVICES(NAME,COST) VALUES('Internet y TV Cable','28');
INSERT INTO KYC_SERVICES(NAME,COST) VALUES('Internet, TV Cable y Netflix','30');

INSERT INTO KYC_SERVICE_STATUS(DESCRIPTION) VALUES('Activo');
INSERT INTO KYC_SERVICE_STATUS(DESCRIPTION) VALUES('Suspendido');
INSERT INTO KYC_SERVICE_STATUS(DESCRIPTION) VALUES('Cancelado');

INSERT INTO KYC_CHANNEL(DESCRIPTION) VALUES('Sucursal');
INSERT INTO KYC_CHANNEL(DESCRIPTION) VALUES('Mobile');
INSERT INTO KYC_CHANNEL(DESCRIPTION) VALUES('Online');

INSERT INTO KYC_PAYMENT_METHODS(DESCRIPTION) VALUES('Ventanilla Bancaria');
INSERT INTO KYC_PAYMENT_METHODS(DESCRIPTION) VALUES('Paypal');
INSERT INTO KYC_PAYMENT_METHODS(DESCRIPTION) VALUES('Tarjeta de Credito');
INSERT INTO KYC_PAYMENT_METHODS(DESCRIPTION) VALUES('Tiendas de autoservicio');

INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Aguascalientes','AS');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Baja California','BC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Baja California Sur','BS');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Campeche','CC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Chiapas','CS');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Chihuahua','CH');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Ciudad de Mexico','DF');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Coahuila','CL');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Colima','CM');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Durango','DG');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Guanajuato','GT');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Guerrero','GR');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Hidalgo','HG');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Jalisco','JC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Estado de Mexico','MC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Michoacan','MN');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Morelos','MS');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Nayarit','NT');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Nuevo Leon','NL');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Oaxaca','OC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Puebla','PL');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Queretaro','QO');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Quintana Roo','QR');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('San Luis Potosi','SP');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Sinaloa','SL');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Sonora','SR');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Tabasco','TC');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Tamaulipas','TS');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Tlaxcala','TL');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Veracruz','VZ');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Yucatan','YN');
INSERT INTO KYC_STATES_COUNTRY(DESCRIPTION,CODE) VALUES('Zacatecas','ZS');

INSERT INTO KYC_PAYMENT_STATUS(DESCRIPTION) VALUES('REJECTED');
INSERT INTO KYC_PAYMENT_STATUS(DESCRIPTION) VALUES('PAID');
INSERT INTO KYC_PAYMENT_STATUS(DESCRIPTION) VALUES('ONGOING');

INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('SUCCESS');
INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('APPROVED');
INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('PENDING');
INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('SEND');
INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('DECLINED');
INSERT INTO KYC_TRANSACTION_STATUS(DESCRIPTION) VALUES('FAILED');

INSERT INTO KYC_USER_TYPE(DESCRIPTION) VALUES('CUSTOMER');
INSERT INTO KYC_USER_TYPE(DESCRIPTION) VALUES('EXECUTIVE');
INSERT INTO KYC_USER_TYPE(DESCRIPTION) VALUES('SYSTEM');

INSERT INTO KYC_BATCH_ID(DESCRIPTION) VALUES('KYC-BATCH-EXECUTIVES-JOB-ADM-EXECUTIVES');
INSERT INTO KYC_BATCH_ID(DESCRIPTION) VALUES('KYC-BATCH-BRANCHES-JOB-UPDATE-BRANCHES');

INSERT INTO KYC_BATCH_STATUS(DESCRIPTION) VALUES('FAILED');
INSERT INTO KYC_BATCH_STATUS(DESCRIPTION) VALUES('SUCCEEDED');
INSERT INTO KYC_BATCH_STATUS(DESCRIPTION) VALUES('ONGOING');

INSERT INTO KYC_REPORT_TYPE(DESCRIPTION) VALUES('APPLICATION FORM');
INSERT INTO KYC_REPORT_TYPE(DESCRIPTION) VALUES('PAYMENT RECEIPT');
INSERT INTO KYC_REPORT_TYPE(DESCRIPTION) VALUES('BILL')
INSERT INTO KYC_REPORT_TYPE(DESCRIPTION) VALUES('CONTRACT')

INSERT INTO KYC_STATUS_OFFER(DESCRIPTION) VALUES('UNPUBLISHED');
INSERT INTO KYC_STATUS_OFFER(DESCRIPTION) VALUES('PUBLISHED');
INSERT INTO KYC_STATUS_OFFER(DESCRIPTION) VALUES('ACCEPTED');
INSERT INTO KYC_STATUS_OFFER(DESCRIPTION) VALUES('EXPIRED');

INSERT INTO KYC_OFFICE VALUES(0,'KYC','MEXICO','MEXICO','MEXICO','MEXICO','00000','L-V 00:00 a 24:00',NULL,NULL,TRUE,0);

-- USERS
INSERT INTO KYC_USER (USERNAME, SECRET, ACTIVE, LOCKED, DATE_CREATION,USER_TYPE) VALUES('KYC_USERS',NULL,TRUE,FALSE,CURRENT_DATE,3);

-- PARAMETERS
INSERT INTO KYC_PARAMETERS(PARAM_KEY,PARAM_VALUE,CREATION_DATE) VALUES('KYC_SHARED_KEY','G+KbPeShVmYq3t6w9z$C&E)H@McQfTjW',CURRENT_DATE);
INSERT INTO KYC_PARAMETERS(PARAM_KEY,PARAM_VALUE,creation_date) VALUES('KYC_SESSION_TIMEOUT','15',CURRENT_DATE);
INSERT INTO KYC_PARAMETERS(PARAM_KEY,PARAM_VALUE,creation_date) VALUES('KYC_FAIL_LOGIN_ATTEMPTS','3',CURRENT_DATE);